# Run All Services
services:
  # Run Service
  # streamlit-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8501:8501
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   volumes:
  #     - ./src:/app/src

  # Run Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/app/apps/api/src


